server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
#          uri: ${HOME}/Desktop/config
           uri: https://github.com/Jerriodaddy/Spring-Cloud-Demo
           search-paths: cloud_conf
           default-label: main
           deleteUntrackedBranches: true
           skipSslValidation: true

